let numero1= 12;
let numero2= 8;
let suma = numero1+numero2;
let resta = numero1-numero2;
let multiplicacion = numero1*numero2;
let division = numero1/numero2;
console.log(suma);
console.log(resta);
console.log(multiplicacion);
console.log(division);
